# use gpu?
gpu: false

# eye blink: 
#   adaptive / svm
method: 'adaptive'

# svm
svm:
  frames: 13
  model: "svm/svm_13.pkl"

adaptive:
  frames: 15
  frames_long: 25
  eye_move_frames: 10
  eye_move_thres: 30
  sensi: 0.84
